FROM python:3.10-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Pre-download NLTK data
RUN python -m nltk.downloader punkt stopwords wordnet
..
ENV PORT=8080

CMD exec gunicorn --bind :$PORT --workers 1 --timeout 0 flask_api:app
